services:
  postgres:
    image: postgres:14
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
