- name: DDDプロジェクトの環境セットアップ
  hosts: local
  become: yes
  tasks:
    - name: パッケージキャッシュを更新
      apt:
        update_cache: yes

    - name: パッケージインストールに必要なパッケージをインストール
      apt:
        name:
          - zip
          - curl
          - git
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: パッケージインストールに必要なパッケージをインストール（SDK）
      shell: |
        curl -s "https://get.sdkman.io" | bash
      args:
        warn: false

    - name: OpenJDK をインストール
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Java のバージョン確認
      command: java -version

    - name: gradle をインストール
      shell: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradle 8.13
      args:
        executable: /bin/bash

    - name: Gradle のバージョン確認
      command: gradle -v

    - name: dockerのインストール ~事前準備～
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        apt update
      args:
        executable: /bin/bash

    - name: dockerのインストール
      apt:
        name: docker-ce
        state: present

    - name: dockerのバージョン確認
      command: docker version

    - name: docker-composeのインストール
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash

    - name: docker-composeのバージョン確認
      command: docker-compose -v